// <auto-generated />
using System;
using ApiFarmarciaElvis.Repositorios;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiFarmarciaElvis.Migrations
{
    [DbContext(typeof(ApiFarmarciaElvisContext))]
    [Migration("20190603002251_FarmaciaElvis-v3-AjustesEntidadeUltimaChanceAutorizacao")]
    partial class FarmaciaElvisv3AjustesEntidadeUltimaChanceAutorizacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiFarmaciaElvis.Entidades.UltimaChanceAutorizacao", b =>
                {
                    b.Property<int?>("SequenciaAutorizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ULCH_SQ_AUTORIZACAO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasColumnName("ULCH_CD_BARRAS")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DataVenda")
                        .IsRequired()
                        .HasColumnName("ULCH_DH_VENDA");

                    b.Property<string>("FlagSituacao")
                        .IsRequired()
                        .HasColumnName("ULCH_FL_SITUACAO")
                        .HasMaxLength(1);

                    b.Property<string>("FlagTipoProduto")
                        .IsRequired()
                        .HasColumnName("ULCH_FL_TIPO_PRODUTO")
                        .HasMaxLength(3);

                    b.Property<decimal?>("MenorPreco")
                        .IsRequired()
                        .HasColumnName("ULCH_MENOR_PRECO");

                    b.Property<decimal?>("PercentualDesconto")
                        .HasColumnName("ULCH_PERCENTUAL_DESCONTO");

                    b.Property<decimal?>("PrecoVenda")
                        .IsRequired()
                        .HasColumnName("ULCH_PRECO_VENDA");

                    b.Property<int?>("ULCH_SQ_PRODUTO")
                        .IsRequired();

                    b.HasKey("SequenciaAutorizacao");

                    b.HasIndex("ULCH_SQ_PRODUTO");

                    b.ToTable("UltimaChanceAutorizacao");
                });

            modelBuilder.Entity("ApiFarmaciaElvis.Entidades.UltimaChanceProduto", b =>
                {
                    b.Property<int?>("SequenciaProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ULCH_SQ_PRODUTO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodigoFilial")
                        .IsRequired()
                        .HasColumnName("FILI_CD_FILIAL");

                    b.Property<int?>("CodigoProduto")
                        .IsRequired()
                        .HasColumnName("PRME_CD_PRODUTO");

                    b.Property<DateTime?>("DataVencimento")
                        .IsRequired()
                        .HasColumnName("ULCH_DT_VENCIMENTO");

                    b.Property<string>("FlagAutorizado")
                        .IsRequired()
                        .HasColumnName("ULCH_FL_AUTORIZADO")
                        .HasMaxLength(1);

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnName("ULCH_LOTE")
                        .HasMaxLength(50);

                    b.Property<int?>("Quantidade")
                        .IsRequired()
                        .HasColumnName("ULCH_QUANTIDADE");

                    b.HasKey("SequenciaProduto");

                    b.ToTable("UltimaChanceProduto");
                });

            modelBuilder.Entity("ApiFarmaciaElvis.Entidades.UltimaChanceAutorizacao", b =>
                {
                    b.HasOne("ApiFarmaciaElvis.Entidades.UltimaChanceProduto", "UltimaChanceProduto")
                        .WithMany()
                        .HasForeignKey("ULCH_SQ_PRODUTO")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
